customhost = "employee.cyck8kqhbfrs.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chongjiaxuan-employee"
customregion = "us-east-1"
